version: '3.7'
services:
    
    nestjs-server:
      build: ./requirements/nestjs
      container_name: nestjs
      restart: always
      depends_on:
        - postgres-database
      networks:
        - database
        - webapp
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        ENVIRONMENT: ${ENVIRONMENT}
      ports:
        - ${NESTJS_HOST_PORT}:3000

    postgres-database:
      image: postgres:latest
      container_name: postgres
      restart: always
      networks:
        - database
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        ENVIRONMENT: ${ENVIRONMENT}
      ports:
        - ${POSTGRES_HOST_PORT}:5432
      volumes:
        - postgres-data:/var/lib/postgresql/data

    adminer:
      image: adminer:latest
      container_name: adminer
      restart: always
      depends_on:
        - postgres-database
      networks:
        - database
      ports:
        - ${ADMINER_HOST_PORT}:8080

networks:
  database:
    driver: bridge
  webapp:
    driver: bridge

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/postgres/data
      o: bind