version: '3.7'
services:
    # reactjs-client:
    #   build: ./requirements/reactjs
    #   container_name: reactjs
    #   restart: always

    # nestjs-server:

    postgres-database:
      image: postgres:latest
      container_name: postgres
      restart: always
      networks:
        - database
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
        ENVIRONMENT: ${ENVIRONMENT}
      volumes:
        - postgres-data:/var/lib/postgresql/data

    adminer:
      image: adminer:latest
      container_name: adminer
      restart: always
      depends_on:
        - postgres-database
      networks:
        - database
      ports:
        - ${ADMINER_HOST_PORT}:8080

networks:
  database:
    driver: bridge

volumes:
  postgres-data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/volumes/postgres/shared/data
      o: bind